language: java
# Required to avoid timeout!
# This is still needed when "travis_wait" is used!
sudo: true

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "3pNe/2B0EDYutjOuUOSYmi5X1OvXFwwJD1WuEc13LXl+DMqGprisfTa0zgAKmzUDrdIGUzGp9bXP6kFlpnxgpTVz7kDDnw6RzYxmjNazWTjPh
WR0yz61TQpebBbjE/7CxlUKM01X901GScmqNI5K+kmLLCHhygbSNh3l5P7OLiCdAHTVPEZXWIy1ifeq+nqXYt6erXaedDyE2Caua3cLw68GlJC6tiWCCwpN+
+PavIQSHEX00pBDLxm7vMpfTFJsYLuAn6NqBtqf8WCY+d3zvZ+Aesm87f/xoIEkP2D4r8bjIgThaRMT0MAcIro8HVAdHSAJj0nbL3KdmR2hurKQSBhqKhm7r
5JGlQjvT3Yc5R5/HoJXzH7STYx1GKS5YH2+UN3+miLV0bDpYLbQRQQuSac7HaoXAjK+CxT3WuF6CgD/TBkyZAdDEonrQIeIQAHFzzFwCwsHIU8yyqQ9tehMV
S0T1+dWofRI4SObpxaW6ZrEW/+7RbYmYduzfPIQ+QV9MBAQs2AyeYZeYSsGfLpor4WrbL7bf5w7P3vHTVs6PD4b08ytW3bndwmAUlQN9dvLgJoL9ifGGpK7P
9EQxJMVhBpJ+pauvbRL45pCYRhOda8GPHQ6S7m1M6zkKVDF69phGJN5YuoZKfuoPcsXwQyt9Au136CAZnKN5eKAngSdkVA="

install:
  - travis_wait 20 mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -e
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: oraclejdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
